### ISSUE TITLE
Will this fail the tests when images don't match

### ISSUE THREAD

**Issue by saikrishna321** [rajdeepv/nakal#2]
ping @rajdeepv

**Comment by rajdeepv** [comment]
Yes. If you do - require 'nakal/cucumber'

If you do not use cucumber, you probably need to write a hook.

**Comment by prasadkalgutkar** [comment]
We are trying to execute `nakal_execute` from other places and not step definition, then how we are supposed to do that?

**Comment by rajdeepv** [comment]
@prasadkalgutkar It should work as usual.
